"""Initial migration.

Revision ID: 302d0c1e8aa0
Revises: None
Create Date: 2015-03-04 16:55:21.550833

"""

# revision identifiers, used by Alembic.
revision = '302d0c1e8aa0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('time_note', sa.String(length=140), nullable=True),
    sa.Column('config_note', sa.String(length=140), nullable=True),
    sa.Column('performance_note', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history_plot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('pv', sa.String(length=140), nullable=False),
    sa.Column('archiver_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('downtime_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('downtime', sa.Float(), nullable=True),
    sa.Column('config_changes', sa.Float(), nullable=True),
    sa.Column('delivered', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('history_plot_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('text', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['history_plot_id'], ['history_plot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    op.drop_table('history_event')
    op.drop_table('downtime_data')
    op.drop_table('history_plot')
    op.drop_table('program')
    op.drop_table('report')
    ### end Alembic commands ###
