"""add title to history plot

Revision ID: 446ee9091244
Revises: 4ea0ee7e333c
Create Date: 2015-03-20 03:49:42.111359

"""

# revision identifiers, used by Alembic.
revision = '446ee9091244'
down_revision = '4ea0ee7e333c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_plot', sa.Column('title', sa.String(length=140), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history_plot', 'title')
    ### end Alembic commands ###
