"""Adding display order columns to history plot and program.

Revision ID: 4ea0ee7e333c
Revises: 302d0c1e8aa0
Create Date: 2015-03-06 19:52:06.495790

"""

# revision identifiers, used by Alembic.
revision = '4ea0ee7e333c'
down_revision = '302d0c1e8aa0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_plot', sa.Column('display_order', sa.Integer(), nullable=True))
    op.add_column('program', sa.Column('display_order', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program', 'display_order')
    op.drop_column('history_plot', 'display_order')
    ### end Alembic commands ###
